mossweb/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings 
from django.views.generic.base import RedirectView

urlpatterns = [
    path(settings.HTTP_PREFIX, include([
        path('', RedirectView.as_view(url='plag/'), name='go-home'),
        path('plag/', include('plag.urls')),
        path('admin/', admin.site.urls),
    ]))
]

plag/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:course_id>/', views.course, name='course'),
    path('<int:assignment_id>/upload/', views.upload, name='upload'),
    path('<int:assignment_id>/process/', views.process, name='process'),
    path('<int:assignment_id>/report/', views.report, name='report'),
]

plag/models.py
import os
import logging
import shutil
import zipfile
import mosspy
import datetime

from bs4 import BeautifulSoup

from django.db import models
from django.conf import settings
from django.core.validators import FileExtensionValidator

# Get an instance of a logger
logger = logging.getLogger(__name__)

def current_year():
    return datetime.date.today().year

class Course(models.Model):
    name = models.CharField(max_length=254)
    classe = models.CharField(max_length=5, default='U')
    professor = models.CharField(max_length=254)
    email = models.EmailField()
    year = models.PositiveSmallIntegerField(default=current_year)
    semester = models.PositiveSmallIntegerField(default=1)

    def save(self, *args, **kwargs):
        # Saving specific course named INF01040/INF01073 will trigger the creation of assignments
        inf01040 = False
        if self._state.adding and self.name in ['INF01040', 'INF01073']:
            inf01040 = True

        super().save(*args, **kwargs)

        # Weekly assignments
        for i in range(1, 15):
            lab = Assignment()
            lab.course = self
            lab.name = 'LAB%02d' % i
            lab.save()

            ep = Assignment()
            ep.course = self
            ep.name = 'EP%02d' % i
            ep.save()

        # Tests
        p1 = Assignment()
        p1.course = self
        p1.name = 'P1'
        p1.save()
        p2 = Assignment()
        p2.course = self
        p2.name = 'P2'
        p2.save()
        pr = Assignment()
        pr.course = self
        pr.name = 'Rec'
        pr.save()

        # TODO: Maybe this should be done via a template model

    def __str__(self):
        return '%s - %s (%d/%d)' % (self.name, self.classe, self.year, self.semester)

    class Meta:
        ordering = ['year', 'semester', 'classe', 'name']

# Define file upload path and filename
def upload_filename(instance, filename):
    name, extension = os.path.splitext(filename)
    dirname = instance.upload_dirname()
    output = '%s/%s%s' % (dirname, instance.name, extension) 
    return output.replace(' ', '_')

class Assignment(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    upload = models.FileField(upload_to=upload_filename, null=True, blank=True, validators=[FileExtensionValidator(allowed_extensions=('zip',))])

    def upload_dirname(self):
        dirname = '%s/uploads/%s' % (settings.UPLOADS_ROOT, str(self.course).replace('/','-'))
        return dirname.replace(' ', '_')

    def extract_dirname(self):
        dirname = '%s/extract/%s/%s' % (settings.UPLOADS_ROOT, str(self.course).replace('/','-'), self.name)
        return dirname.replace(' ', '_')

    def report_dirname(self):
        dirname = '%s/reports/%s/%s' % (settings.UPLOADS_ROOT, str(self.course).replace('/','-'), self.name)
        return dirname.replace(' ', '_')

    def report_filename(self):
        dirname = self.report_dirname()
        return '%s/report.html' % dirname

    def is_uploaded(self):
        return os.path.exists(str(self.upload))

    def is_processed(self):
        return os.path.exists(self.report_filename())

    def load_report(self):
        if not self.is_processed():
            raise self.AssignmentException(
                'No report has been created for assignment %s' %
                self.name
            )
        output = ''
        with open(self.report_filename(), 'r') as file:
            data = file.read()
            output += data
        soup = BeautifulSoup(output, 'lxml')
        body = soup.find('body')
        # Shorten filenames by removing path prefix
        for td in body.find_all('td'):
            a = td.find('a')
            if a:
                a.string = a.string.replace('%s/' % self.extract_dirname(), '')
                a['target'] = '_blank'

        # Adding Bootstrap style to table
        table = body.find('table')
        if table:
            table['class'] = 'table table-striped'

        return body.prettify()

    # Extract assignments from zip file (Moodle assignment style)
    def extract(self):
        if(not(self.upload)): # No file has been uploaded
            raise self.AssignmentException(
                'No file has been uploaded to assignment %s' %
                self.name
            )
        with zipfile.ZipFile(self.upload) as zip_file:
            for member in zip_file.namelist():
                filename = os.path.basename(member)
                # skip directories
                if not filename:
                    continue

                # skip non-C source files
                if not filename.endswith(('.c', '.cpp')):
                    continue

                # copy file (taken from zipfile's extract)
                source = zip_file.open(member)
                # create new name based on the directory name i.e. student's name
                # in Moodle's zip standard there is an _file_ at the end of the directory's name
                if '_file_' in member:
                    newname = member[0:member.index('_')].replace(' ', '_') + '_' + filename
                else:
                    newname = member.replace('/', '_')

                target_dir = self.extract_dirname()
                if not os.path.exists(target_dir):
                    os.makedirs(target_dir)
                target = open(os.path.join(target_dir, newname), "wb")
                with source, target:
                    shutil.copyfileobj(source, target)
        return True

    # Run the moss similarity check web service
    def moss(self):
        m = mosspy.Moss(settings.MOSS_USERID, "c")
        extract_dir = self.extract_dirname()
        if not os.path.exists(extract_dir):
            raise self.AssignmentException(
                'It seems like the zip file for assignment %s has not been extracted' %
                self.name
            )
        m.addFilesByWildcard('%s/*.c' % extract_dir)
        url = m.send()

        logger.info('Report URL: %s ' % url)

        # Save report file
        report_dir = self.report_dirname()
        if not os.path.exists(report_dir):
            os.makedirs('%s/%s' % (report_dir, 'report/'))
        m.saveWebPage(url, "%s/report.html" % report_dir)

        # mosspy.download_report(url, '%s/report/' % report_dir, connections=8, log_level=10) # logging.DEBUG (20 to disable)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']

    class AssignmentException(Exception):

        def __init__(self, msg):
            self.msg = msg
            logger.warning(msg)

        def __str__(self):
            return repr(self.msg)

plag/forms.py
from django import forms

from .models import Assignment

class AssignmentForm(forms.ModelForm):
    class Meta:
        model = Assignment
        fields = ('upload', )

plag/views.py
import logging

from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import loader
from django.shortcuts import render, redirect
from django.contrib import messages

from .models import Course
from .models import Assignment
from .forms import AssignmentForm

# Get an instance of a logger
logger = logging.getLogger(__name__)

def index(request):

    courses = Course.objects.all()

    template = loader.get_template('plag/index.html')
    context = {
        'courses': courses,
    }

    return HttpResponse(template.render(context, request))

def course(request, course_id):

    try:
        course = Course.objects.get(pk=course_id)
    except:
        raise Http404("Course does not exist")

    return render(request, 'plag/course.html', {'course': course})

def report(request, assignment_id):
    try:
        assignment = Assignment.objects.get(pk=assignment_id)
    except:
        raise Http404("Assignment does not exist")

    return render(request, 'plag/report.html', {'assignment': assignment})

def upload(request, assignment_id):
    try:
        assignment = Assignment.objects.get(pk=assignment_id)
    except:
        raise Http404("Assignment does not exist")

    if request.method == 'POST':
        form = AssignmentForm(request.POST, request.FILES, instance=assignment)
        if form.is_valid():
            form.save()
            msg = "Assignment %s uploaded successfully" % assignment.name
            messages.success(request, msg)
            logger.info(msg)
            return redirect('course', assignment.course.id)
    else:
        form = AssignmentForm(instance=assignment)

    return render(request, 'plag/upload.html', {'assignment': assignment, 'form': form})

def process(request, assignment_id):
    try:
        assignment = Assignment.objects.get(pk=assignment_id)
    except:
        raise Http404("Assignment does not exist")

    # First extract files
    try:
        assignment.extract()
    except assignment.AssignmentException as e:
        msg = "Could not extract file %s: %s" % (assignment.upload, str(e))
        messages.warning(request, msg)
        logger.warning(msg)

    try:
        assignment.moss()
    except Exception as e:
        msg = "Could not run similarity check for %s: %s" % (assignment.name, str(e))
        messages.warning(request, msg)
        logger.warning(msg)

    msg = "Report created for %s" % assignment.name
    messages.success(request, msg)
    logger.info(msg)
    return redirect('course', assignment.course.id)

plag/templates/plag/base.html
{% load static %}
<!doctype html>
<html lang="en">
	<head>
		<!-- Required meta tags -->
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<!-- Bootstrap CSS -->
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

		<link rel="stylesheet" type="text/css" href="{% static 'plag/style.css' %}" />
		<title>{% block title %}Plagiarism Check{% endblock %}</title>
	</head>
	<body>
		<div class="container">
			{% if messages %}
				{% for message in messages %}
				<div class="alert {{ message.tags }} alert-dismissible" role="alert">
					<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				    {{ message }}
				</div>
				{% endfor %}
			{% endif %}
		{% block content %}{% endblock %}
		</div>
		<!-- Optional JavaScript -->
		<!-- jQuery first, then Popper.js, then Bootstrap JS -->
		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
	</body>
</html>

plag/templates/plag/course.html
{% extends 'plag/base.html' %}
{% block content %}
<h1>{{ course }}</h1>

<dl>
	<dt>Course: </dt>
	<dd>{{ course.name}} (Class {{ course.classe}})</dd>
	<dt>Professor: </dt>
	<dd>{{ course.professor}} (<a href="mailto:{{ course.email}}">{{ course.email}}</a>)</dd>
	<dt>Semester: </dt>
	<dd>{{ course.year }}/{{ course.semester }}</dd>
</dl>

<h2>Assignments</h2>
<table class="table table-striped">
	<thead>
		<tr>
			<th>Assignment</th>
			<th>Actions</th>
		</tr>
	</thead>
	<tbody>
		{% for a in course.assignment_set.all %}
		<tr>
			<td>{{ a }}</td>
			<td>
				<a href="{% url 'upload' a.id %}" class="btn btn-primary btn-sm" role="button">Upload</a>
				{% if a.is_uploaded %}
				<a href="{% url 'process' a.id %}" class="btn btn-primary btn-sm" role="button">Check Similarity</a>
				{% else %}
				<a href="#" class="btn btn-primary btn-sm disabled" role="button">Check Similarity</a>
				{% endif %}
				{% if a.is_processed %}
				<a href="{% url 'report' a.id %}" class="btn btn-primary btn-sm" role="button">View Report</a>
				{% else %}
				<a href="#" class="btn btn-primary btn-sm disabled" role="button">View Report</a>
				{% endif %}
			</td>
		</tr>
	{% endfor %}
	</tbody>
</table>
<a href="{% url 'index' %}" class="btn btn-primary" role="button">Go back</a>
{% endblock %}

plag/templates/plag/index.html
{% extends 'plag/base.html' %}
{% block content %}
<h1>Courses</h1>
{% if courses %}
<table class="table table-striped">
	<thead>
		<tr>
			<th>Course</th>
			<th>Class</th>
			<th>Professor</th>
			<th>Semester</th>
			<th>Actions</th>
		</tr>
	</thead>
	<tbody>
    		{% for c in courses %}
		<tr>
			<td>{{ c.name }}</td>
			<td>{{ c.classe }}</td>
			<td>{{ c.professor }}</td>
			<td>{{ c.year }}/{{ c.semester }}</td>
			<td><a href="{% url 'course' c.id %}" class="btn btn-primary btn-sm" role="button">View</a></td>
		</tr>
    		{% endfor %}
	</tbody>
</table>
{% else %}
    <p>No courses available.</p>
{% endif %}
{% endblock %}

plag/templates/plag/report.html
{% extends 'plag/base.html' %}
{% block content %}
<h1>Report for {{ assignment.course }} {{ assignment }}</h1>

{% if assignment.is_processed %}
{{ assignment.load_report | safe }}
{% endif %}
<a href="{% url 'course' assignment.course.id %}" class="btn btn-primary" role="button">Go back</a>
{% endblock %}

plag/templates/plag/upload.html
{% extends 'plag/base.html' %}
{% block content %}
<h1>Uploading file for {{ assignment.course }} {{ assignment }}</h1>

{% if error_message %}<div class="alert alert-danger" role="alert">{{ error_message }}</div>{% endif %}

<form action="{% url 'upload' assignment.id %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% for field in form %}
        <div class="form-group">
        {% if field.errors %}<div class="alert alert-danger" role="alert">{{ field.errors }}</div>{% endif %}
        {{ field.label_tag }} {{ field }}
        {% if field.help_text %}
        <small id="uploadHelp" class="form-text text-muted">{{ field.help_text|safe }}</small>
        {% endif %}
    </div>
    {% endfor %}
    <input class="btn btn-primary" role="button" type="submit" value="Send">
</form>
<br/>
<a href="{% url 'course' assignment.course.id %}" class="btn btn-primary" role="button">Go back</a>
{% endblock %}